config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search_histories/index'
  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :publisher, presence: true
  validates :pbulished_year, presence: true, numericality: { only_integer: true }
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :current_visitor

  def current_visitor
    @current_visitor ||= User.find_by(id: session[:visitor_id]) || create_current_visitor
  end

  def create_current_visitor
    last_user = User.last
    last_user_id = if last_user.nil?
                     0
                   else
                     last_user.id
                   end
    new_user = User.create(ref: last_user_id + 1)
    session[:visitor_id] = new_user.id

    new_user
  end

  # GET /articles or /articles.json
  def index
    store_search_history(params[:query]) if params[:query].present?
    @articles = if params[:query].present?
                  Article.where('lower(title) LIKE ?', "%#{params[:query].downcase}%")
                else
                  Article.all
                end

    if turbo_frame_request?
      render partial: 'articles', locals: { articles: @articles }
    else
      render :index
    end
  end

  def store_search_history(search_data)
    search_history = SearchHistory.where(user: @current_visitor).order('created_at')
    puts 'Search History: '
    p search_data
    single_search = search_related(search_history, search_data)
    p single_search
    if single_search
      single_search.update(search_string: search_data)
    else
      SearchHistory.create(search_string: search_data, user: @current_visitor)
    end
  end

  def search_related(search_history, search_data)
    search_history.each do |history|
      return history if search_data.include? history.search_string
    end
    nil
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :publisher, :pbulished_year)
  end
end

app/controllers/search_histories_controller.rb
class SearchHistoriesController < ApplicationController
  def index
    @search_histories = SearchHistory.includes(:user)
    p @search_histories[0].user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_histories_helper.rb
module SearchHistoriesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="card flex-col">
    <div class='flex-row gap'>
      <div class='author-avatar'>
      <img class='author-avatar' src="https://thumbs.dreamstime.com/b/avatar-van-de-geekmens-104871313.jpg" alt="author image"></div>
      <h4>
        <%= article.publisher %>
      </h5>

      <h6>
        <strong>year:</strong>
        <%= article.pbulished_year %>
      </h6>
    </div>
    <h3>
      <%= link_to article.title, article_path(article) %>
    </h3>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag 'articles' do %>
  <%= render articles %>
<%end%>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='flex-col gap'>  
      <%= form.text_field :title, class: 'text-field', placeholder: 'Article Title' %>

      <%= form.text_field :publisher, class: 'text-field', placeholder: 'Article Publisher' %>

      <%= form.number_field :pbulished_year, class: 'text-field', placeholder: 'Published Year' %>

      <%= form.submit 'Create Article', class: 'btn' %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div class='flex gap'>
  <%= link_to "Show this article", @article, class:'btn margin-top' %> 
  <%= link_to "Back to articles", articles_path, class:'btn margin-top' %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>
<div class='flex-col'>
  <h1>Articles</h1>
  <%= form_with(url: articles_path, class: 'flex-col gap',method: :get, data:{ controller: 'search-form', turbo_frame: 'articles', turbo_action: 'advance'}) do |f|%>
    <%= f.label :query, 'Search for article'%>
    <%= f.text_field :query, class: 'text-field',data: {action:'input->search-form#search'}%>

    <%= f.submit 'Search', class: 'btn self-end'%>
  <%end%>

  <%= render 'articles', articles: @articles%>

  <%= link_to "New article", new_article_path, class: 'btn margin-top' %>
  <%= link_to "Show Search History", search_histories_index_path, class: 'btn margin-top' %>
</div>

app/views/articles/new.html.erb
<div>
  <%= link_to '< Back', articles_path%>
</div>

<h1>New article</h1>

<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div class = 'flex-col'>
  <div class='flex gap'>
    <%= link_to "Edit this article", edit_article_path(@article), class:'btn margin-top' %> 
    <%= link_to "Back to articles", articles_path, class:'btn margin-top' %>
  </div>

  <%= button_to "Destroy this article", @article, method: :delete, class:'btn-destroy margin-top' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'style.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search_histories/index.html.erb
<div>
  <%= link_to '< Back', articles_path%>
</div>
<h1>SearchHistories</h1>
<% @search_histories.each do |history|%>
  <div class= 'card'>
    <h4>Search value: <%= history.search_string%></h4>
    <p>User ID: <%= history.user.id%> </p>
  </div>
<%end%>